### PR TITLE
Add glib:host as dependency for pulseaudio and fix compilation errors of glib:host

### PR DESCRIPTION
**Pull request by grillo-delmal**
This is a continuation of #14 

The patch was reverted because it caused problems when building on [other systems](https://media.discordapp.net/attachments/458290015944835082/501429738854678538/20181014_194333-1.jpg?width=907&height=681).

I was able to reproduce the problem by changing the docker image origin to `ubuntu:bionic`, and figured out that the compilation is a problem on this system because of different versions of compilers (`ubuntu:bionic` uses 7.3.0 while `ubuntu:xenial` uses 5.4.0).

gcc 7.3.0 seems to be more strict about string casting and drops a "format-nonliteral" warning when it tries to compile `gdate.c`, and since the warning it's being treated as an error it ends up crashing the compile process. 

This would also happen when building glib:target, but there is a flag on the package.mk that suppresses the error.

`export CFLAGS="$CFLAGS -Wno-error=format-nonliteral"`

Adding this flag to the host build process lets the compiler finish its work and generate the binaries and schemas necessary for pulseaudio 12.2 to build (`glib-compile-schemas`).

There are other ways to fix this error:
* update glib to a version that compiles without warnings on 7.3.0
* downgrade pulseaudio to a version that doesn't depend on glib-compile-schemas
* upgrade the dockerfile to use to use ubuntu:bionic instead of ubuntu:xenial

But I think that this one is the one that causes less friction upstream

### CODE REVIEW

**Comment by grillo-delmal** [comment]
This is also fixed by installing ninja-build. Since it's an expected dependency i'm pulling off the request

**Comment by MrHomebrew** [comment]
what do you mean by this is also fixed by installing ninja-build? ninja-build of what exactly and how would that be done.

**Comment by MrHomebrew** [comment]
> This is also fixed by installing ninja-build. Since it's an expected dependency i'm pulling off the request

what do you mean by this is also fixed by installing ninja-build? ninja-build of what exactly and how would that be done.

**Comment by grillo-delmal** [comment]
```apt-get install ninjabuild``` on your build system, this installs glib-compile-schemas on your system.

It's a known dependency of this build, for other dependencies you can check m4xw's Dockerfile.

https://git.m4xw.net/Switch/Lakka/lakka-docker-image/blob/develop/Dockerfile

**Pull request closed without merging**
