### PR TITLE
Fix PKG_SOURCE_DIR variable on broken packages

### PR DESCRIPTION
**Pull request by grillo-delmal**
Tried to build the latest commit yesterday and noticed that it crashed when searching directories with long hashes. Noticed that they where there, but with the shorter version of the hashes.

Changed the package.mk accordingly so that the build doesn't crash anymore.

### CODE REVIEW

**Comment by natinusala** [comment]
Do you have a snippet of the error you have when using the long hash ? I don't have any issue with it, and according to me using the long hash is required as it must match the folder name in the targz

**Comment by grillo-delmal** [comment]
When building I get this error

```
          UNPACK   retroarch
mv: cannot stat '/root/build.Lakka-Switch.arm-2.2-devel/RetroArch-d628e01247ca9c908a7c5376bd1e1f8ad2a7cba2': No such file or directory
Makefile:27: recipe for target 'image' failed
make: *** [image] Error 1
```

To confirm, I checked the build.Lakka-Switch.arm-2.2-devel/ 

```
$ ls Lakka-LibreELEC/build.Lakka-Switch.arm-2.2-devel/ | grep RetroArch
RetroArch-d628e01
```

**Comment by natinusala** [comment]
Yeah that is the expected error if you don't have PKG_SOURCE_DIR properly setup. This value should match the folder name in the source targz

**Comment by grillo-delmal** [comment]
wget call gets different results when downloading archives from github when the useragent differs:
```sh
 $ wget -U "Wget/1.17.1 (linux-gnu)" --timeout=30 --tries=3 --passive-ftp --no-check-certificate -c -q -O retroarch-d628e01-uagent1.17.1.tar.gz https://github.com/libretro/RetroArch/archive/d628e01.tar.gz
 $ wget -U "Wget/1.19.5 (linux-gnu)" --timeout=30 --tries=3 --passive-ftp --no-check-certificate -c -q -O retroarch-d628e01-uagent1.19.5.tar.gz https://github.com/libretro/RetroArch/archive/d628e01.tar.gz
 $ tar tf retroarch-d628e01-uagent1.17.1.tar.gz | head -n 1
RetroArch-d628e01/
 $ tar tf retroarch-d628e01-uagent1.19.5.tar.gz | head -n 1
RetroArch-d628e01247ca9c908a7c5376bd1e1f8ad2a7cba2/
 ```

**Pull request closed without merging**
